alias: notify_if_insecure_when_late
trigger:
  - platform: time
    at: '22:00:00'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: cover.garage_door
    state: open
  - condition: state
    entity_id: binary_sensor.front_door_open
    state: 'on'
action:
  - service: notify.html5
    data_template:
      title: The house is insecure and its getting late
      message: >-
        {% if is_state('cover.garage_door', 'open') and is_state('binary_sensor.front_door_open', 'on') %}
          The garage door is open and the front door is open
        {% elif is_state('cover.garage_door', 'open') %}
          The garage door is open
        {% else %}
          The front door is open
        {% endif %}
      data: 
        url: >-
          {% if is_state('binary_sensor.front_door_open', 'on') %}
            https://williamson-ave.duckdns.org/api/camera_proxy_stream/camera.entrance_phone?token={{ state_attr('camera.entrance_phone', 'access_token') }}
          {% elif is_state('cover.garage_door', 'open') %}
            https://williamson-ave.duckdns.org/api/camera_proxy_stream/camera.garage_phone?token={{ state_attr('camera.garage_phone', 'access_token') }}
          {% else %}
            https://williamson-ave.duckdns.org/api/camera_proxy_stream/camera.entrance_phone?token={{ state_attr('camera.entrance_phone', 'access_token') }}
          {% endif %}
        tag: ha-notify
        image: >-
          {% if is_state('binary_sensor.front_door_open', 'on') %}
            https://williamson-ave.duckdns.org{{ state_attr('camera.entrance_phone', 'entity_picture') }}
          {% elif is_state('cover.garage_door', 'open') %}
            https://williamson-ave.duckdns.org{{ state_attr('camera.garage_phone', 'entity_picture') }}
          {% else %}
            https://williamson-ave.duckdns.org{{ state_attr('camera.entrance_phone', 'entity_picture') }}
          {% endif %}  
        actions: 
        - title: Lock up     
          action: lock_up