alias: notify_if_insecure_when_late
trigger:
  - platform: time
    at: '22:00:00'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: cover.garage_door
    state: open
  - condition: state
    entity_id: binary_sensor.front_door_open
    state: on
action:
  - service: notify.html5
    data_template:
      title: The house is unlocked and its getting late
      message: >-
        {% if is_state('cover.garage_door', 'open') and is_state('binary_sensor.front_door_open', 'on') %}
          The garage door is open and the front door is open
        {% elif is_state('cover.garage_door', 'open') %}
          The garage door is open
        {% else %}
          The front door is open
        {% endif %}
      data: 
        url: https://williamson-ave.duckdns.org
        actions: 
        - title: Lock up     
          action: lock_up