alias: off_if_heatpump_on_when_late
trigger:
  - platform: time
    at: '22:00:00'
condition:
  - condition: template
    value_template: "{{ states.climate.living_room_heatpump != 'off' }}"
action:
  - service: climate.set_operation_mode
    data:
      entity_id: climate.living_room_heat_pump      
      operation_mode: off
  # - service: notify.html5
  #   data_template:
  #     title: The heat pump is on and its getting late
  #     message: The living room heatpump is still on
  #     data: 
  #       url: https://williamson-ave.duckdns.org
