version: '2'

services:
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.couchpotato:/config
      - /home/bradley/Downloads:/downloads
      - /media/bradley/external/Videos:/movies
    ports:
      - "5050:5050"
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: "host"
    restart: unless-stopped
    environment:
      - VERSION=latest
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.plex:/config
      - /media/bradley/external/Videos:/movies
      - /media/bradley/external/TV Shows:/tvshows
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.transmission:/config
      - /home/bradley/Downloads:/downloads
      - /home/bradley/Torrents:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
  sickrage:
    image: linuxserver/sickrage
    container_name: sickrage 
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.sickrage:/config
      - /home/bradley/Downloads:/downloads
      - /media/bradley/external/TV Shows:/tv
    ports:
      - "8082:8081"
  home-assistant:
    image: homeassistant/home-assistant
    container_name: hass
    restart: unless-stopped
    network_mode: "host"
    devices:
      - /dev/ttyACM0
    environment: 
      - VIRTUAL_PORT=8123
      - VIRTUAL_HOST=williamson-ave.duckdns.org
      - LETSENCRYPT_HOST=williamson-ave.duckdns.org
      - LETSENCRYPT_EMAIL=bradley.s.scott@gmail.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./homeassistant:/config
  unifi:
    image: linuxserver/unifi
    container_name: unifi
    restart: unless-stopped
    volumes: 
      - ./unifi:/config
    environment:
      - PGID=999
      - PUID=999
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8880:8880"
  caddy:
    image: abiosoft/caddy:0.10.11
    container_name: caddy
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy:/root/.caddy
  intesis-mqtt:
    build: intesis_mqtt/.
    container_name: intesis_mqtt
    network_mode: "host"
    restart: unless-stopped
  pi-hole:
    image: diginc/pi-hole
    container_name: pi-hole
    restart: unless-stopped
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=NZ
      - ServerIP=192.168.1.167
    ports:
      - "88:80"
      - "53:53/tcp"
      - "53:53/udp"