version: '2'

services:
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: always
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.couchpotato:/config
      - /home/bradley/Downloads:/downloads
      - /media/bradley/external/Videos:/movies
    ports:
      - "5050:5050"
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: "host"
    restart: always
    environment:
      - VERSION=latest
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.plex:/config
      - /media/bradley/external/Videos:/movies
      - /media/bradley/external/TV Shows:/tvshows
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.transmission:/config
      - /home/bradley/Downloads:/downloads
      - /home/bradley/Torrents:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
  sickrage:
    image: linuxserver/sickrage
    container_name: sickrage 
    restart: always
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - /home/bradley/.sickrage:/config
      - /home/bradley/Downloads:/downloads
      - /media/bradley/external/TV Shows:/tv
    ports:
      - "8082:8081"
  home-assistant:
    image: homeassistant/home-assistant
    container_name: hass
    restart: always
    network_mode: "host"
    depends_on:
      - https-nginx-proxy-companion
    devices:
      - /dev/ttyACM0
    environment: 
      - VIRTUAL_PORT=8123
      - VIRTUAL_HOST=williamson-ave.duckdns.org
      - LETSENCRYPT_HOST=williamson-ave.duckdns.org
      - LETSENCRYPT_EMAIL=bradley.s.scott@gmail.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./homeassistant:/config
  unifi:
    image: linuxserver/unifi
    container_name: unifi
    restart: always
    volumes: 
      - ./unifi:/config
    environment:
      - PGID=999
      - PUID=999
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8880:8880"
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports: 
      - "80:80"
      - "443:443"
  https-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on: 
      - nginx-proxy
    volumes: 
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from: 
      - nginx-proxy
    environment:
      - DEBUG=true