version: '2'

services:
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./.couchpotato:/config
      - /media/bradley/external/downloads/complete:/downloads
      - /media/bradley/external/movies:/movies
    ports:
      - "5050:5050"
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: "host"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=999
      - TZ=Pacific/Auckland
    volumes:
      - ./.jellyfin:/config
      - /media/bradley/external/tv:/data/tvshows
      - /media/bradley/external/movies:/data/movies
      - /media/bradley/external/dvr:/data/dvr
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./.transmission:/config
      - /media/bradley/external/downloads:/downloads
      - /media/bradley/external/torrents:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
  sickrage:
    image: linuxserver/sickrage
    container_name: sickrage 
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ./.sickrage:/config
      - /media/bradley/external/downloads/complete:/downloads
      - /media/bradley/external/tv:/tv
    ports:
      - "8082:8081"
  home-assistant:
    image: homeassistant/home-assistant
    container_name: hass
    restart: unless-stopped
    network_mode: "host"
    depends_on: 
      - mosquitto
    devices:
      - /dev/ttyACM0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./homeassistant:/config
    privileged: true
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./.mosquitto/config:/mosquitto/config
      - ./.mosquitto/data:/mosquitto/data
      - ./.mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  entrance-cam:
    image: kerberos/kerberos
    container_name: entrance-cam
    volumes:
      - ./.kerberos/config/entrance-cam:/etc/opt/kerberosio/config
      - /media/bradley/external/security/entrance-cam:/etc/opt/kerberosio/capture
      - ./.kerberos/logs/entrance-cam:/etc/opt/kerberosio/logs
      - ./.kerberos/kerberos.php:/var/www/web/config/kerberos.php
    ports:
      - "881:80"
  garage-cam:
    image: kerberos/kerberos
    container_name: garage-cam
    volumes:
      - ./.kerberos/config/garage-cam:/etc/opt/kerberosio/config
      - /media/bradley/external/security/garage-cam:/etc/opt/kerberosio/capture
      - ./.kerberos/logs/garage-cam:/etc/opt/kerberosio/logs
      - ./.kerberos/kerberos.php:/var/www/web/config/kerberos.php
    ports:
      - "882:80"
  cube-cam:
    image: kerberos/kerberos
    container_name: cube-cam
    volumes:
      - ./.kerberos/config/cube-cam:/etc/opt/kerberosio/config
      - /media/bradley/external/security/cube-cam:/etc/opt/kerberosio/capture
      - ./.kerberos/logs/cube-cam:/etc/opt/kerberosio/logs
      - ./.kerberos/kerberos.php:/var/www/web/config/kerberos.php
    ports:
      - "883:80"