version: '2'

services:
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - ./.couchpotato:/config
      - /media/bradley/external/downloads:/downloads
      - /media/bradley/external/movies:/movies
    ports:
      - "5050:5050"
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: "host"
    restart: unless-stopped
    environment:
      - VERSION=latest
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - ./.plex:/config
      - /media/bradley/external/movies:/movies
      - /media/bradley/external/tv:/tvshows
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - ./.transmission:/config
      - /media/bradley/external/downloads:/downloads
      - /media/bradley/external/torrents:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
  sickrage:
    image: linuxserver/sickrage
    container_name: sickrage 
    restart: unless-stopped
    environment:
      - PGID=999
      - PUID=999
      - TZ=Pacific/Auckland
    volumes:
      - ./.sickrage:/config
      - /media/bradley/external/downloads:/downloads
      - /media/bradley/external/tv:/tv
    ports:
      - "8082:8081"
  home-assistant:
    image: homeassistant/home-assistant
    container_name: hass
    restart: unless-stopped
    network_mode: "host"
    depends_on: 
      - mosquitto
      - mysql
    devices:
      - /dev/ttyACM0
    environment: 
      - VIRTUAL_PORT=8123
      - VIRTUAL_HOST=williamson-ave.duckdns.org
      - LETSENCRYPT_HOST=williamson-ave.duckdns.org
      - LETSENCRYPT_EMAIL=bradley.s.scott@gmail.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./homeassistant:/config
    privileged: true
  mysql:
    image: mysql/mysql-server
    container_name: mysql
    restart: unless-stopped
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment: 
      - MYSQL_DATABASE=home-assistant
      - MYSQL_USER=homeassistant
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./.mysql/my.cnf:/etc/my.cnf
      - ./.mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
  unifi:
    image: linuxserver/unifi
    container_name: unifi
    restart: unless-stopped
    volumes: 
      - ./.unifi:/config
    environment:
      - PGID=999
      - PUID=999
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8880:8880"
  caddy:
    image: abiosoft/caddy:0.10.11
    container_name: caddy
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./.mosquitto/config:/mosquitto/config
      - ./.mosquitto/data:/mosquitto/data
      - ./.mosquitto/log:/mosquitto/log
  entrance-cam:
    image: kerberos/kerberos
    container_name: entrance-cam
    volumes:
      - ./kerberos/config/entrance-cam:/etc/opt/kerberosio/config
      - /media/bradley/external/security/entrance-cam:/etc/opt/kerberosio/capture
      - ./kerberos/logs/entrance-cam:/etc/opt/kerberosio/logs
      - ./kerberos/kerberos.php:/var/www/web/config/kerberos.php
    ports:
      - "881:80"
  garage-cam:
    image: kerberos/kerberos
    container_name: garage-cam
    volumes:
      - ./kerberos/config/garage-cam:/etc/opt/kerberosio/config
      - /media/bradley/external/security/garage-cam:/etc/opt/kerberosio/capture
      - ./kerberos/logs/garage-cam:/etc/opt/kerberosio/logs
      - ./kerberos/kerberos.php:/var/www/web/config/kerberos.php
    ports:
      - "882:80"
  cube-cam:
    image: kerberos/kerberos
    container_name: cube-cam
    volumes:
      - ./kerberos/config/cube-cam:/etc/opt/kerberosio/config
      - /media/bradley/external/security/cube-cam:/etc/opt/kerberosio/capture
      - ./kerberos/logs/cube-cam:/etc/opt/kerberosio/logs
      - ./kerberos/kerberos.php:/var/www/web/config/kerberos.php
    ports:
      - "883:80"



