alias: arm_alarm_when_leaving
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'off'
    for: 
      minutes: 5
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: disarmed
action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.alarm
      code: !secret alarm_code