alias: start_camera_when_away
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'off'
    for: 
      minutes: 5
action:
  - service: switch.turn_on
    data:
      entity_id: switch.garage_camera_rtsp_server
  - service: switch.turn_on
    data:
      entity_id: switch.cube_cam_rtsp_server
