alias: stop_camera_when_home
trigger:
  - platform: state
    entity_id: device_tracker.nirupa_pixel3
    to: 'home'
  - platform: state
    entity_id: device_tracker.bradley_pixel3
    to: 'home'
action:
  - service: shell_command.stop_cube_cam
