alias: turn_off_lights_when_leaving
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'off'
    for: 
      minutes: 5
condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: group.all_lights