alias: turn_off_switch_when_leaving
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'off'
    for: 
      minutes: 5
condition:
  - condition: state
    entity_id: switch.smart_switch
    state: 'on'
action:
  - service: switch.turn_off
    entity_id: switch.smart_switch