alias: turn_off_heatpumps_when_leaving
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'off'
    for: 
      minutes: 5
condition:
  condition: or
  conditions:
  - condition: template
    value_template: "{% if is_state('climate.living_room_heat_pump', 'Off') %}false{% else %}true{% endif %}"
  - condition: template
    value_template: "{% if is_state('climate.bedroom_heat_pump', 'Off') %}false{% else %}true{% endif %}"
action:
  - service: climate.set_operation_mode
    entity_id: climate.bedroom_heat_pump
    data:
      operation_mode: 'Off'
  - service: climate.set_operation_mode
    entity_id: climate.living_room_heat_pump      
    data:
      operation_mode: 'Off'
