alias: turn_off_heatpumps_when_leaving
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'off'
    for: 
      minutes: 5
condition:
  condition: or
  conditions:
  - condition: template
    value_template: "{% if is_state('climate.living_room_heatpump', 'off') %}false{% else %}true{% endif %}"
  - condition: template
    value_template: "{% if is_state('climate.bedroom_heatpump', 'off') %}false{% else %}true{% endif %}"
action:
  - service: climate.turn_off
    entity_id: climate.bedroom_heatpump
  - service: climate.turn_off
    entity_id: climate.living_room_heatpump