alias: notify_action_bathroom_off
trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: bathroom_off
action:
  - service: switch.turn_off
    data:
      entity_id: group.bathroom
