alias: notify_action_sound_siren
trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: sound_siren
action:
  - service: switch.turn_on
    data:
      entity_id: switch.siren_2