alias: notify_action_sound_siren
trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: sound_siren
action:
  - service: switch.turn_on
    data:
      entity_id: switch.siren
  - service: notify.phone
    data:
      message: "Hello. The alarm at home has been triggered and the siren is ringing. The siren will ring for at least 2 minutes. You can turn it off sooner using Home Assistant or by using the kill switch in the garage. Goodbye"
      target:
        - "+6421538400"
        - "+64210512656"