alias: notify_action_switch_off
trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: switch_off
action:
  - service: switch.turn_off
    entity_id: switch.smart_switch