alias: hide_doorbell_camera
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_doorbell_motion
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
action:
  - service: group.set_visibility
    entity_id: group.doorbell_camera
    data:
      visible: False