alias: show_doorbell_camera
trigger:
  - platform: template
    value_template: "{{ is_state('binary_sensor.front_door_doorbell_motion', 'on') }}"
action:
  - service: group.set_visibility
    entity_id: group.doorbell_camera
    data:
      visible: True