homeassistant:
  # Name of the location where Home Assistant is running
  name: Williamson Ave
  # Location required to calculate the time the sun rises and sets
  latitude: -36.8594849
  longitude: 174.7467815
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 16
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: williamson-ave.duckdns.org
  trusted_networks:
#    - 127.0.0.1
#    - ::1
#    - 192.168.1.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Covers
cover:
# Open Garage
  platform: opengarage
  covers:
    garage:
      host: 192.168.1.130
      device_key: !secret opengarage_devicekey
      name: Garage door

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
   
# Notifications
notify:
 - name: pushbullet
   platform: pushbullet
   api_key: !secret pushbullet_api_key
 - name: html5
   platform: html5
   gcm_api_key: !secret gcm_server_key
   gcm_sender_id: !secret gcm_sender_id

   # IFTT automation
ifttt:
  key: !secret ifttt_key
  
# Z Wave configuration
zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true

# Wink to enable August smartlock integration
august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

# Alarm control panel
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code
    pending_time: 30 # secs to leave after arm
    delay_time: 30 # secs to disarm 

sensor: !include_dir_list sensors
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
#konnected: !include konnected.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml