homeassistant:
  # Name of the location where Home Assistant is running
  name: Williamson Ave
  # Location required to calculate the time the sun rises and sets
  latitude: -36.8594849
  longitude: 174.7467815
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 16
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  # Customization file
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://williamson-ave.duckdns.org
  trusted_networks:
#    - 127.0.0.1
#    - ::1
#    - 192.168.1.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - temperature_high
      - temperature_low
      - precip_intensity_max
      - uv_index

# Text to speech
tts:
  - platform: google

# IFTT automation
ifttt:
  key: !secret ifttt_key
  
# Z Wave configuration
zwave:
  usb_path: /dev/ttyACM0

alarm_control_panel: !include configuration/alarm_control_panel.yaml
android_ip_webcam: !include configuration/android_ip_webcam.yaml
august: !include configuration/august.yaml
automation: !include_dir_list automation
binary_sensor: !include_dir_list configuration/binary_sensors
camera: !include configuration/camera.yaml
cover: !include configuration/cover.yaml
cloud: !include configuration/cloud.yaml
device_tracker: !include configuration/device_tracker.yaml
ffmpeg:
group: groups.yaml
history: !include configuration/history.yaml
input_boolean: !include configuration/input_boolean.yaml
intesishome: !include configuration/intesishome.yaml
logbook: !include configuration/logbook.yaml
konnected: !include configuration/konnected.yaml
mqtt: !include configuration/mqtt.yaml
nest: !include configuration/nest.yaml
notify: !include configuration/notify.yaml
owntracks: !include configuration/owntracks.yaml
recorder: !include configuration/recorder.yaml
shell_command: !include_dir_merge_named configuration/shell_command
script: !include_dir_merge_named scripts
sensor: !include_dir_list configuration/sensors
twilio: !include configuration/twilio.yaml
zone: !include zones.yaml