homeassistant:
  # Customization file
  customize: !include_dir_merge_named customize

  # Enabled Dwains theme
  #packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

# Enables the frontend
frontend:
  # themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://ti8au3j9khhkqc282u9frizwjfelxkag.ui.nabu.casa

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

system_health:

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# IFTT automation
ifttt:
  key: !secret ifttt_key
  
# Z Wave configuration
zwave:
  usb_path: /dev/ttyACM0

# Wemo
wemo:
  discovery: true
  static: 
    - 192.168.13.13
    
alarm_control_panel: !include configuration/alarm_control_panel.yaml
android_ip_webcam: !include configuration/android_ip_webcam.yaml
august: !include configuration/august.yaml
automation: !include_dir_list automation
binary_sensor: !include_dir_list configuration/binary_sensors
camera: !include configuration/camera.yaml
climate: !include configuration/climate.yaml
cover: !include configuration/cover.yaml
cloud:
device_tracker: !include configuration/device_tracker.yaml
ffmpeg:
group: !include groups.yaml
history: !include configuration/history.yaml
input_boolean: !include configuration/input_boolean.yaml
logbook: !include configuration/logbook.yaml
konnected: !include configuration/konnected.yaml
mqtt: !include configuration/mqtt.yaml
notify: !include configuration/notify.yaml
person: 
recorder: !include configuration/recorder.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_list configuration/sensors
shell_command: !include_dir_merge_named configuration/shell_command
stream:
twilio: !include configuration/twilio.yaml
zone: !include zones.yaml