default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.alarm
    - group.doors
    - group.automation

weather_view:
  view: yes
  icon: mdi:weather-hail
  entities:
    - group.weather
    - group.climate
    - switch.pedestal_fan

media_view:
  view: yes
  icon: mdi:music
  entities:
    - media_player.master_bedroom_home
    - media_player.compucast
    - configurator.plex_media_server

automation:
  name: Automation
  entities: 
    - automation.notify_if_door_is_open_when_its_1030pm	
    - automation.notify_if_door_is_open_when_leaving	
    - automation.remind_every_2_hours_when_the_garage_door_is_open
    - automation.trigger_alarm_on_door_open_when_armed_home	
    - automation.trigger_alarm_on_motion_when_armed_away	
  
alarm:
  name: Burglar alarm
  entities:
    - alarm_control_panel.alarm
    - binary_sensor.entrance
    - binary_sensor.guest_bedroom
    - binary_sensor.living_room
    - script.panic_button

doors:
  name: Doors and locks
  entities:
    - cover.garage_door
    - sensor.garage_status
    - sensor.garage_car_present
    - lock.front_door

weather:
  name: Weather outside
  entities:
    - sensor.owm_forecast
    - sensor.owm_condition
    - sensor.owm_rain
    - sensor.owm_temperature
    - sensor.owm_wind_speed
    - sun.sun

climate:
  name: Climate control
  entities:
    - binary_sensor.aeotec_zw100_multisensor_6_sensor
    - sensor.aeotec_zw100_multisensor_6_alarm_level
    - sensor.aeotec_zw100_multisensor_6_alarm_type
    - sensor.aeotec_zw100_multisensor_6_burglar
    - sensor.aeotec_zw100_multisensor_6_luminance
    - sensor.aeotec_zw100_multisensor_6_relative_humidity
    - sensor.aeotec_zw100_multisensor_6_sourcenodeid
    - sensor.aeotec_zw100_multisensor_6_temperature
    - sensor.aeotec_zw100_multisensor_6_ultraviolet
  
