alias: dining_off_during_day
trigger:
  - platform: time_pattern
    minutes: /30
    seconds: 0
condition:
    - condition: numeric_state
      entity_id: sensor.entrance_phone_light_level
      above: 50
action:
  - service: switch.turn_off
    data:
      entity_id: switch.dining_table_light
