alias: dining_off_during_day
trigger:
  - platform: time
    minutes: /30
    seconds: 0
condition:
    - condition: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_luminance
      above: 50
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeotec_zw116_nano_switch_switch # Dining room light
