alias: downstairs_vacant
trigger:
  - platform: state
    entity_id: binary_sensor.entrance
    to: 'off'
    for:
      minutes: 2
action:
  - service: script.turn_on
    data:
      entity_id: script.downstairs_lights_off