alias: downstairs_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'off'
action:
  - service: script.turn_on
    data:
      entity_id: script.downstairs_lights_off
  - service: switch.turn_off
    data:
      entity_id: switch.switch_10 # Garage