alias: downstairs_motion
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_open
    to: 'on'
  - platform: state
    entity_id: binary_sensor.entrance
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id: sensor.entrance_phone_light_level
      below: 50
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -6
action:
  - service: script.turn_on
    data:
      entity_id: script.downstairs_lights_on
     
