alias: garage_vacant
trigger:
  - platform: state
    entity_id: binary_sensor.garagecamera_motion_sensor
    to: 'off'
    for:
      minutes: 10
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch_2 # Garage lights