alias: garage_lights_on
trigger:
  - platform: state
    entity_id: cover.garage_door.attributes["door_state"]
    to: 'opening'
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_luminance
      below: 50
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -6
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeotec_zw116_nano_switch_switch_3 # Garage
  - service: script.turn_on
    entity_id: script.downstairs_lights_on
     
