alias: garage_lights_on
trigger:
  - platform: state
    entity_id: cover.garage_door
    to: 'open'
  - platform: state
    entity_id: binary_sensor.garage_camera_motion_sensor
    to: 'on'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeon_labs_zw116_nano_switch_switch_2 # Garage lights