alias: living_vacant
trigger:
  - platform: state
    entity_id: binary_sensor.living_room
    to: 'off'
condition:
  - condition: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    state: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.aeotec_zw132_dual_nano_switch_switch_4 # Stairs