alias: living_motion
trigger:
  - platform: state
    entity_id: binary_sensor.living_room
    to: 'on'
condition:
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -6
action:
  - service: switch.turn_on
    data:
      entity_id: switch.aeotec_zw132_dual_nano_switch_switch_16 # Stairs
     
