alias: living_motion_stairs_off
trigger:
  - platform: state
    entity_id: binary_sensor.living_room
    to: 'off'
    for:
      minutes: 2
condition:
  - condition: state
    entity_id: binary_sensor.upstairs_motion
    state: 'off'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.upstairs_stairs_light