alias: living_motion_stairs_on
trigger:
  - platform: state
    entity_id: binary_sensor.living_room
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: numeric_state
      entity_id: sensor.entrance_phone_light_level
      below: 30
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -6
action:
  - service: switch.turn_on
    data:
      entity_id: switch.upstairs_stairs_light
     
