alias: upstairs_motion
trigger:
  - platform: state
    entity_id: binary_sensor.upstairs_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.in_bed
      state: 'off'
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.upstairs_light_level
          below: 10000
        - condition: numeric_state
          entity_id: sun.sun
          value_template: '{{ state.attributes.elevation }}'
          below: -6
action:
  - service: script.turn_on
    data:
      entity_id: script.upstairs_lights_on
     
