alias: upstairs_lights_on
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'on'
condition:
  - condition: state
    entity_id: switch.switch_5
    state: 'off'
  - condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
    - condition: sun
      before: sunrise
      before_offset: "1:00:00"
action:
  - service: switch.turn_on
    data:
      entity_id: switch.switch_5
