alias: upstairs_vacant
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'off'
action:
  - service: script.turn_on
    data:
      entity_id: script.upstairs_lights_off
     
