alias: upstairs_lights_off
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'off'
condition:
  - condition: state
    entity_id: switch.switch_5
    state: 'on'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.switch_5
