alias: upstairs_motion
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'on'
condition:
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -6
action:
  - service: script.turn_on
    data:
      entity_id: script.upstairs_lights_on
     
