alias: notify_on_arrival
trigger:
  - platform: state
    entity_id: device_tracker.diemrssv_walleye
    to: 'home'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: device_tracker.diemrssv_jackpotlte
    state: 'not_home'
  - condition: state
    entity_id: cover.garage_door
    state: 'closed'
  - condition: state
    entity_id: sensor.garage_car_present
    state: 'No'
action:
  - service: notify.html5_unnamed_device_2 # B's Pixel 2
    data_template:
      title: Welcome home
      message: The garage is empty and Nirupa isn't home
      data: 
        url: https://williamson-ave.duckdns.org
        actions: 
        - title: Open garage    
          action: open_garage