alias: notify_on_arrival
trigger:
  - platform: state
    entity_id: device_tracker.google_maps_115726181286227444765
    to: 'home'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: device_tracker.galaxya82018
    state: 'not_home'
  - condition: state
    entity_id: cover.garage_door
    state: 'closed'
action:
  - service: notify.html5
    data_template:
      title: Welcome home
      message: The garage is empty and Nirupa isn't home
      target: unnamed_device_2 # B's Pixel 2
      data: 
        url: https://williamson-ave.duckdns.org
        actions: 
        - title: Open garage    
          action: open_garage