alias: notify_on_smoke
trigger:
  - platform: state
    entity_id: sensor.living_room_nest_protect_smoke_status
    to: 'Emergency'
condition:
  - condition: state
    entity_id: binary_sensor.home_occupied
    state: 'off'
action:
  - service: notify.html5
    data_template:
      title: There is a problem at home
      message: The smoke alarm has detected a fire
      data: 
        tag: ha-notify
        url: https://williamson-ave.duckdns.org