alias: bedroom_on_in_morning_if_cold
trigger:
  - platform: time
    at: '05:30:00'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sensor.owm_temperature
    below: '16'
  - condition: state
    entity_id: binary_sensor.home_occupied
    state: 'on'
action:
  - service: climate.turn_on
    entity_id: climate.bedroom_heat_pump
  - service: climate.set_operation_mode
    entity_id: climate.bedroom_heat_pump
    data:
      operation_mode: 'heat' 
