alias: bedroom_on_in_morning_if_cold
trigger:
  - platform: time
    at: '05:45:00'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sensor.upstairs_temperature
    below: '17.5'
  - condition: state
    entity_id: binary_sensor.home_occupied
    state: 'on'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bedroom_heatpump
      hvac_mode: 'heat' 
  - service: climate.set_fan_mode
    data:
      entity_id: climate.bedroom_heatpump
      fan_mode: 'Low'
