alias: bedroom_on_in_morning_if_cold
trigger:
  - platform: time
    at: '05:45:00'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sensor.bedroom_temp
    below: '17'
  - condition: state
    entity_id: binary_sensor.home_occupied
    state: 'on'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: climate.set_operation_mode
    data:
      entity_id: climate.bedroom_heat_pump
      operation_mode: 'heat' 
  - service: climate.set_fan_mode
    data:
      entity_id: climate.bedroom_heat_pump
      fan_mode: 'quiet' 
