alias: bedroom_heatpump_off_in_morning
trigger:
  - platform: time
    at: '05:00:00'
condition:
  - condition: state
    entity_id: climate.bedroom_heat_pump
    state: 'Cool'
action:
  - service: climate.set_hvac_mode
    entity_id: climate.bedroom_heat_pump
    data:
      hvac_mode: 'off'
