alias: bedroom_on_in_morning_if_cold
trigger:
  - platform: time
    at: '05:45:00'
condition:
  condition: and
  conditions:
  - condition: numeric_state
    entity_id: sensor.aeotec_zw100_multisensor_6_temperature
    below: '17.5'
  - condition: state
    entity_id: binary_sensor.home_occupied
    state: 'on'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: climate.set_operation_mode
    data:
      entity_id: climate.bedroom_heat_pump
      operation_mode: 'Heat' 
  - service: climate.set_fan_mode
    data:
      entity_id: climate.bedroom_heat_pump
      fan_mode: 'Quiet' 
