alias: notify_if_bathroom_lights_on
trigger:
  - platform: time
    minutes: /30
    seconds: 0
condition:
  - condition: state
    entity_id: group.bathroom_lights
    state: 'on'
    for:
      minutes: 45
action:
  - service: notify.html5
    data_template:
      title: Bathroom lights are on
      message: The bathroom lights are on. Don't forget to turn them off
      data: 
        url: https://williamson-ave.duckdns.org
        actions: 
        - title: Turn off 
          action: bathroom_off