alias: notify_if_garage_open
trigger:
  - platform: time_pattern
    hours: /2
    minutes: 0
    seconds: 0
condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
action:
  - service: notify.html5
    data_template:
      title: Remember the garage door is open
      message: The garage door is open. Remember to check the garage belongings are secure
      data: 
        tag: ha-notify
        url: /lovelace/cameras
        image: /api/camera_proxy/camera.garage_camera
        actions: 
        - title: Close garage   
          action: close_garage
  - service: notify.mobile_apps
    data_template:
      title: Remember the garage door is open
      message: The garage door is open. Remember to check the garage belongings are secure
      data: 
        clickAction: /lovelace/camera
        image: /api/camera_proxy/camera.garage_camera
        actions: 
        - title: Close garage   
          action: close_garage
                    