alias: notify_if_bathroom_fan_on
trigger:
  - platform: time
    minutes: /30
    seconds: 0
condition:
  - condition: state
    entity_id: switch.switch_7 # Bathroom fan
    state: 'on'
    for:
      minutes: 45
action:
  - service: notify.html5
    data_template:
      title: Bathroom fan on
      message: The bathroom fan is on. Don't forget to turn it off
      data: 
        url: https://williamson-ave.duckdns.org
        actions: 
        - title: Turn off 
          action: bathroom_off