alias: notify_if_doors_open
trigger:
  - platform: time_pattern
    minutes: /30
    seconds: 0
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: lock.front_door
    state: 'unlocked'
  - condition: state
    entity_id: binary_sensor.front_door_open
    state: 'on'
action:
  - service: notify.html5
    data_template:
      title: The front door is open
      message: The front door is open. Remember to check the house belongings are secure
      data: 
        tag: ha-notify
        url: /lovelace/cameras
  - service: notify.mobile_apps
    data_template:
      title: The front door is open
      message: The front door is open. Remember to check the house belongings are secure
      data: 
        clickAction: /lovelace/camera
        image: /api/camera_proxy/camera.entrance_phone
