alias: disarm_when_home
trigger:
  - platform: state
    entity_id: person.bradley
    to: 'home'
  - platform: state
    entity_id: person.nirupa
    to: 'home'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: pending
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: triggered
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm
      code: !secret alarm_code
  - service: switch.turn_off
    data:
      entity_id: switch.buzzer
  - service: notify.html5
    data_template:
      title: Alarm disarmed
      message: >-
        {% if is_state('person.nirupa', 'home') and is_state('person.bradley', 'home') %}
          The alarm has disarmed because everyone is now home
        {% elif is_state('person.nirupa', 'home') %}
          The alarm has disarmed because Nirupa has arrived home
        {% else %}
          The alarm has disarmed because Bradley has arrived home
        {% endif %}
      data:
        tag: ha-alarm
  - service: notify.mobile_apps
    data_template:
      title: Alarm disarmed
      message: >-
        {% if is_state('person.nirupa', 'home') and is_state('person.bradley', 'home') %}
          The alarm has disarmed because everyone is now home
        {% elif is_state('person.nirupa', 'home') %}
          The alarm has disarmed because Nirupa has arrived home
        {% else %}
          The alarm has disarmed because Bradley has arrived home
        {% endif %}
      data:
        image: /api/camera_proxy/camera.front_door_doorbell
