alias: disarm_when_home
trigger:
  - platform: state
    entity_id: device_tracker.diemrssv_jackpotlte
    to: 'home'
  - platform: state
    entity_id: device_tracker.diemrssv_walleye
    to: 'home'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: pending
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm
      code: !secret alarm_code
  - service: script.turn_on
    entity_id: script.notify_subscribers
    data:
      variables:
        title: Alarm disarmed
        message: >-
          {% if is_state('device_tracker.diemrssv_jackpotlte', 'home') %}
            The alarm has disarmed because Nirupa has arrived home
          {% else %}
            The alarm has disarmed because Bradley has arrived home
          {% endif %}