alias: disarm_when_home
trigger:
  - platform: state
    entity_id: device_tracker.diemrssv_jackpotlte
    to: 'home'
  - platform: state
    entity_id: device_tracker.diemrssv_walleye
    to: 'home'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: pending
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm
      code: !secret alarm_code
  - service: notify.html5
    data_template:
      title: Alarm disarmed
      message: >-
        {% if is_state('device_tracker.diemrssv_jackpotlte', 'home') and is_state('device_tracker.diemrssv_walleye', 'home') %}
          The alarm has disarmed because everyone is now home
        {% elif is_state('device_tracker.diemrssv_jackpotlte', 'home') %}
          The alarm has disarmed because Nirupa has arrived home
        {% else %}
          The alarm has disarmed because Bradley has arrived home
        {% endif %}
      data:
        url: https://williamson-ave.duckdns.org{{ state_attr('camera.front_door_doorbell', 'entity_picture') }}
        tag: ha-alarm
        image: https://williamson-ave.duckdns.org{{ state_attr('camera.front_door_doorbell', 'entity_picture') }}