alias: disarm_when_home
trigger:
  - platform: state
    entity_id: binary_sensor.home_occupied
    to: 'on'
    for:
      minutes: 0
      seconds: 30
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm
      code: !secret alarm_code
  - service: script.turn_on
    entity_id: script.notify_subscribers
    data:
      variables:
        title: Alarm disarmed
        message: The alarm has disarmed due to someone arriving home