alias: disarm_when_home
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'home'
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.alarm
  - service: script.turn_on
    entity_id: script.notify_subscribers
    data:
      variables:
        title: Alarm disarmed
        message: The alarm has disarmed due to someone arriving home