alias: disarm_when_home
trigger:
  - platform: state
    entity_id: device_tracker.nirupa_pixel3
    to: 'home'
  - platform: state
    entity_id: device_tracker.bradley_pixel3
    to: 'home'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: pending
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: triggered
action:
  - service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.alarm
      code: !secret alarm_code
  - service: switch.turn_off
    data:
      entity_id: switch.buzzer
  - service: notify.html5
    data_template:
      title: Alarm disarmed
      message: >-
        {% if is_state('device_tracker.nirupa_pixel3', 'home') and is_state('device_tracker.bradley_pixel3', 'home') %}
          The alarm has disarmed because everyone is now home
        {% elif is_state('device_tracker.nirupa_pixel3', 'home') %}
          The alarm has disarmed because Nirupa has arrived home
        {% else %}
          The alarm has disarmed because Bradley has arrived home
        {% endif %}
      data:
        tag: ha-alarm
        image: https://ti8au3j9khhkqc282u9frizwjfelxkag.ui.nabu.casa{{ state_attr('camera.front_door_doorbell', 'entity_picture') }}