alias: silence_siren
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    from: 'triggered'
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'disarmed'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.siren
  - service: group.set_visibility
    entity_id: group.doorbell_camera
    data:
      visible: False
  - service: switch.turn_off
    data:
      entity_id: switch.buzzer