alias: sound_siren_on_alarm
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'triggered'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.siren
  - service: switch.turn_off
    data:
      entity_id: switch.buzzer_2
  - service: notify.phone
    data:
      message: "Hello. The alarm at home has been triggered and the siren is ringing. The siren will ring for at least 2 minutes. You can turn it off sooner using Home Assistant or by using the kill switch in the garage. Goodbye"
      target:
        - "+6421538400"
        - "+64210512656"