alias: triggers_when_armed_home
trigger:
  - platform: state
    entity_id: cover.garage_door
    to: 'Opening'
  - platform: state
    entity_id: binary_sensor.front_door_open
    to: 'on'
  - platform: state
    entity_id: binary_sensor.garage_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.entrance
    to: 'on'
  - platform: state
    entity_id: binary_sensor.guest_bedroom
    to: 'on'
  - platform: state
    entity_id: binary_sensor.living_room
    to: 'on'
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_home
action:
  - service: script.turn_on
    entity_id: script.notify_on_alarm
    data_template: 
      variables:
        trigger: >-
          {% if is_state('binary_sensor.front_door_open', 'on') %}
            The front door opening
          {% elif is_state('cover.garage_door', 'Opening') %}
            The garage door opening
          {% elif is_state('binary_sensor.garage_motion', 'on') %}
            Movement in the garage
          {% elif is_state('binary_sensor.entrance', 'on') %}
            Movement at the entrance
          {% elif is_state('binary_sensor.guest_bedroom', 'on') %}
            Movement in the guest bedroom
          {% else %}
            Movement in the living room
          {% endif %}
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm