alias: triggers_when_armed_away
trigger:
  - platform: state
    entity_id: group.motion_sensors
    to: 'on'
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_away
  - condition: state
    entity_id: binary_sensor.home_occupied
    state: 'off'
action:
  - service: script.turn_on
    entity_id: script.notify_on_motion
    data_template: 
      variables:
        trigger: >-
          {% if is_state('binary_sensor.entrance', 'on') %}
            Movement at the entrance
          {% elif is_state('binary_sensor.guest_bedroom', 'on') %}
            Movement in the guest bedroom
          {% elif is_state('binary_sensor.living_room', 'on') %}
            Movement in the living room
          {% else %}
            Movement upstairs
          {% endif %}
        image: >-
          {% if is_state('binary_sensor.entrance', 'on') %}
            https://williamson-ave.duckdns.org{{ state_attr('camera.entrance_phone', 'entity_picture') }}
          {% endif %}
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm
  - service: switch.turn_on
    data:
      entity_id: switch.buzzer