alias: trigger_on_door_when_home
trigger:
  - platform: state
    entity_id: cover.garage_door
    to: 'opening'
  - platform: state
    entity_id: lock.front_door
    to: 'unlocked'
condition:
  - condition: state
    entity_id: alarm_control_panel.alarm
    state: armed_home
action:
  - service: script.turn_on
    entity_id: script.notify_on_alarm
    data_template: 
      variables:
        trigger: >-
          {% if is_state('cover.garage_door', 'opening') and is_state('lock.front_door', 'unlocked') %}
            The garage door opening and front door unlocking
          {% elif is_state('cover.garage_door', 'opening') %}
            The garage door opening
          {% else %}
            The front door unlocking
          {% endif %}
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm