alias: warn_before_arm
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    from: 'disarmed'
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'pending'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.buzzer

alias: turn_warn_off_when_armed_away
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    from: 'pending'
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'armed_away'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.buzzer

alias: turn_warn_off_when_armed_home
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    from: 'pending'
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'armed_home'
action:
  - service: switch.turn_off
    data:
      entity_id: switch.buzzer