alias: notify_if_raining_and_door_open
trigger:
  - platform: template
    value_template: "{{ not(is_state('sensor.owm_rain', 'not raining')) and not(is_state('sensor.owm_rain', '0.0')) }}"
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: binary_sensor.aeotec_zw112_door_window_sensor_6_sensor # Left hand deck door 
    state: 'on'
  - condition: state
    entity_id: binary_sensor.aeotec_zw112_door_window_sensor_6_sensor_2 # Right hand deck door
    state: 'on'
action:
  - service: notify.html5
    data_template:
      title: It is raining the deck doors are open
      message: >-
        {% if is_state('binary_sensor.aeotec_zw112_door_window_sensor_6_sensor', 'on') and is_state('binary_sensor.aeotec_zw112_door_window_sensor_6_sensor_2', 'on') %}
          Both the left side and the right side deck doors are open
        {% elif is_state('binary_sensor.aeotec_zw112_door_window_sensor_6_sensor', 'on') %}
          The left side deck door is open
        {% else %}
          The right side deck door is open
        {% endif %}
      data: 
        url: /states/group.climate_view
        tag: ha-notify