alias: notify_if_rain_forecast_and_door_open
trigger:
  - platform: template
    value_template: "{{ not(is_state('sensor.owm_rain', 'not raining')) and not(is_state('sensor.owm_rain', '0.0')) }}"
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: binary_sensor.left_deck_door
    state: 'on'
  - condition: state
    entity_id: binary_sensor.right_deck_door
    state: 'on'
action:
  - service: notify.html5
    data_template:
      title: Rain is forecast and the deck doors are open
      message: >-
        {% if is_state('binary_sensor.left_deck_door', 'on') and is_state('binary_sensor.right_deck_door', 'on') %}
          Both the left side and the right side deck doors are open
        {% elif is_state('binary_sensor.left_deck_door', 'on') %}
          The left side deck door is open
        {% else %}
          The right side deck door is open
        {% endif %}
      data: 
        url: /lovelace/climate
        tag: ha-notify
