alias: notify_if_insecure_in_bed
trigger:
  - platform: state
    entity_id: binary_sensor.in_bed
    to: 'on'
condition:
  condition: and
  conditions: 
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: cover.garage_door
      state: open
    - condition: state
      entity_id: lock.front_door
      state: unlocked
action:
  - service: notify.html5
    data_template:
      title: The house is insecure and its getting late
      message: >-
        {% if is_state('cover.garage_door', 'open') and is_state('lock.front_door', 'unlocked') %}
          The garage door is open and the front door is unlocked
        {% elif is_state('cover.garage_door', 'open') %}
          The garage door is open
        {% else %}
          The front door is unlocked
        {% endif %}
      data: 
        tag: ha-notify
        url: /lovelace/cameras
        image: >-
          {% if is_state('cover.garage_door', 'open') %}
            /api/camera_proxy/camera.garage_camera
          {% else %}
            /api/camera_proxy/camera.entrance_phone
          {% endif %}  
        actions: 
        - title: Lock up     
          action: lock_up