alias: off_if_heatpump_on_when_late
trigger:
  - platform: state
    entity_id: binary_sensor.in_bed
    to: 'on'
condition:
  - condition: template
    value_template: "{{ not(is_state('climate.living_room_heatpump', 'off')) }}"
action:
  - service: climate.turn_off
    entity_id: climate.living_room_heatpump
  - service: notify.html5
    data_template:
      title: The heat pump was on and it was getting late
      message: I have turned the living room heatpump off for you
      data: 
        tag: ha-notify