alias: off_if_heatpump_on_when_late
trigger:
  - platform: state
    entity_id: sensor.in_bed
    to: 'on'
condition:
  - condition: template
    value_template: "{{ not(is_state('climate.living_room_heat_pump', 'off')) }}"
action:
  - service: climate.set_operation_mode
    entity_id: climate.living_room_heat_pump      
    data:
      operation_mode: 'off'
  - service: notify.html5
    data_template:
      title: The heat pump was on and it was getting late
      message: I have turned the living room heatpump off for you
      data: 
        tag: ha-notify