# External connectivity
- platform: ping
  host: google.com
  name: Internet connection
  
# Presence detection
- platform: template
  sensors:
    home_occupied:
      friendly_name: Home occupied
      value_template: >-
        {{ is_state('group.all_devices', 'home') }}   
