- platform: generic
  name: Cube cam
  still_image_url: http://192.168.1.248/cgi-bin/currentpic.cgi
  username: !secret webcam_username
  password: !secret webcam_password
- platform: ffmpeg
  name: Garage camera
  input: !secret pancam_rstp
